name: for all testing (frontend e2e and backend unit testing).

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  all-test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files in the frontend folder
        id: changed-files-frontend
        uses: tj-actions/changed-files@v42
        with:
          files: frontend/**

      - name: Test Frontend
        if: steps.changed-files-frontend.outputs.all_changed_and_modified_files_count != 0
        env:
          FRONTEND_CHANGED_COUNT: ${{ steps.changed-files-frontend.outputs.all_changed_and_modified_files_count }}
        uses: ./.github/workflows/frontend.yml
      
      - name: Not Test Frontend
        if: steps.changed-files-frontend.outputs.all_changed_and_modified_files_count == 0
        run: |
          echo "FRONTEND: NOT CHANGED..."

      - name: Get changed files in the backend folder
        id: changed-files-backend
        uses: tj-actions/changed-files@v42
        with:
          files: backend/**
  
      - name: Test Backend
        if: steps.changed-files-backend.outputs.all_changed_and_modified_files_count != 0
        env:
          BACKEND_CHANGED_COUNT: ${{ steps.changed-files-backend.outputs.all_changed_and_modified_files_count }}
        uses: ./.github/workflows/backend.yml

      - name: Not Test Backend
        if: steps.changed-files-backend.outputs.all_changed_and_modified_files_count == 0
        run: |
          echo "BACKEND: NOT CHANGED..."
  
  