name: masterdock backend unit test

on:
  workflow_call:

defaults:
  run:
    working-directory: backend

jobs:
  backend-test:
    runs-on: self-hosted
    steps:
      - name: Prepare for test
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test
        run: |
          pytest