name: masterdock backend unit test

on:
  push:
    paths:
      - 'backend/**'

defaults:
  run:
    working-directory: backend

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        - run: echo "This is backend."