name: masterdock backend unit test

on:
  push:
    paths:
      - 'backend/**'

defaults:
  run:
    working-directory: backend

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run test
        run: pytest