name: masterdock frontend e2e test

on:
  workflow_call:

defaults:
  run:
    working-directory: frontend

env:
  CYPRESS_KEY: ${{vars.CYPRESS_KEY}}

jobs:
  frontend-test:
    runs-on: self-hosted
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install yarn
        run: corepack enable

      - name: prepare for test
        run: |
          yarn install

      - name: Run test
        run: |
          if [ "${{ env.CYPRESS_KEY }}" == "" ]; then
            yarn test:e2e:ci
          else
            yarn test:e2e:ci:record
          fi
