name: masterdock frontend e2e test

on:
  push:
    paths:
      - 'frontend/**'

defaults:
  run:
    working-directory: frontend

env:
  CYPRESS_KEY: ${{vars.CYPRESS_KEY}}

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: prepare for test
        run: |
          yarn install

      - name: Run test
        run: |
          yarn test:e2e:ci:record